@startuml
'https://plantuml.com/class-diagram

Order --> "1" User
Ticket --> "1" Concert
Order "1" *-- "many" Ticket
class User{
    - username : String

    - emailAddress : String

    + User(String username, String emailAddress) : void
    +getUserName() : String
    +getEmailAddress() : String
}



class Concert{
    - name : String
    - venue : String
    - city : String

    + Concert(String name, String venue, String city) : void
    + getName() : String
    + getVenue() : String
    + getCity() : String

}

class Ticket{
    - date : DateTime
    - concert : Concert
    - price : double

    + Ticket(DateTime date, Concert concert, double price) : void
    + getDate() : DateTime
    + getPrice() : double
    + getConcert() : Concert
}

class Order{
    - tickets : ArrayList
    - user : User
    - payment : Payment
    - platform : Platform

    + Order(ArrayList tickets, User user, Platform platform) : void
    + calculateOrderAmount():double
    + sendTickets() : void

}

Order "1" --> "1" Payment
interface Payment{
+takePayment(amount:double):boolean
}

class CreditCardPayment implements Payment{
-creditCardNumber: int
-expiryDate: date
-cvv:int
+takePayment(amount:double):boolean
}

class DebitCardPayment implements Payment{
-debitCardNumber: int
-expiryDate: date
-cvv:int
+takePayment(amount:double):boolean
}

class PaypalPayment implements Payment{
+takePayment(amount:double):boolean
}

enum Platform{
    iOS
    Android
    Desktop
}
@enduml